/**
 * PR drafting for accumulated optimization wins.
 * Pushes the optimize branch and creates a draft PR with metrics.
 */

import { execFileSync } from "child_process";
import type { OptimizeState } from "./types.js";
import { pushBranch } from "./git-ops.js";
import { readResults, deltaPercent } from "./results.js";
import { writeOptimizeState } from "./state.js";
import { notifyPrDrafted } from "./notify.js";
import { createLogger } from "../log.js";

const log = createLogger("optimize:pr");

export function draftPr(
  repoRoot: string,
  branch: string,
  state: OptimizeState,
): void {
  // Push the branch
  try {
    pushBranch(repoRoot, branch);
  } catch (err) {
    log(`Push failed: ${err}`);
    return;
  }

  // Build PR body from results
  const results = readResults(repoRoot);
  const wins = results.filter((r) => r.status === "keep");
  const discards = results.filter((r) => r.status === "discard");
  const crashes = results.filter((r) => r.status === "crash");

  const baselineP50 = state.baseline_p50_ms;
  const currentP50 = state.current_p50_ms;
  const totalDelta = baselineP50 > 0
    ? deltaPercent(baselineP50, currentP50).toFixed(1)
    : "N/A";

  const winList = wins
    .map((w) => `- \`${w.commit}\` ${w.description} (${w.delta_pct.toFixed(1)}%)`)
    .join("\n");

  const body = `## Summary

Autonomous pipeline optimization — ${wins.length} improvements found.

**Screening latency (p50)**: ${baselineP50}ms → ${currentP50}ms (**${totalDelta}% improvement**)

## Optimizations Applied

${winList || "None yet"}

## Experiment Stats

| Metric | Value |
|--------|-------|
| Total experiments | ${results.length} |
| Wins (kept) | ${wins.length} |
| Discards | ${discards.length} |
| Crashes | ${crashes.length} |
| Win rate | ${results.length > 0 ? ((wins.length / results.length) * 100).toFixed(0) : 0}% |

## Verification

- \`npm run verify\`: All wins passed before being kept
- Benchmark: 15 diverse EINs, cached SQLite data (no live API calls)
- Threshold: >=5% p50 improvement required to keep

---
Generated by nightshift optimize (autoresearch pattern)`;

  try {
    const prUrl = execFileSync(
      "gh",
      [
        "pr",
        "create",
        "--draft",
        "--title",
        `perf: optimize screening pipeline (p50 ${baselineP50}ms → ${currentP50}ms)`,
        "--body",
        body,
      ],
      { cwd: repoRoot, encoding: "utf-8" },
    ).trim();

    log(`Draft PR created: ${prUrl}`);
    notifyPrDrafted(prUrl);

    // Update state in place — caller passes the live state object
    state.last_pr_url = prUrl;
    state.wins_since_pr = 0;
    writeOptimizeState(state);
  } catch (err) {
    log(`PR creation failed: ${err}`);
  }
}
